version: '3'

services:
  video-streaming:
    image: py-video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
      target: prod
    container_name: py-video-streaming
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - RABBIT=amqp://guest:guest@rabbit:5672
    restart: 'no'
    depends_on:
      - db
      - rabbit

  video-storage:
    image: py-video-storage
    build:
      context: ./video-storage-azure
      dockerfile: Dockerfile
      target: prod
    container_name: py-video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
    restart: 'no'

  db:
    image: mongo:4.2
    container_name: py-db
    ports:
      - "4002:27017"
    restart: always

  history:
    image: py-history
    build:
      context: ./history
      dockerfile: Dockerfile
      target: prod
    container_name: py-history
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - RABBIT=amqp://guest:guest@rabbit:5672
    restart: 'no'
    depends_on:
      - db
      - rabbit

  rabbit:
    image: rabbitmq:3.8-management
    container_name: py-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672
    restart: always
