version: '3'

services:
  video-streaming:
    image: py-video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: py-video-streaming
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
    restart: 'no'

  video-storage:
    image: py-video-storage
    build:
      context: ./video-storage-azure
      dockerfile: Dockerfile
    container_name: py-video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
    restart: 'no'

  db:
    image: mongo:4.2
    container_name: py-db
    ports:
      - "4002:27017"
    restart: always

