version: '3'

services:
  video-streaming:
    image: py-video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
      target: dev
    container_name: py-video-streaming
    ports:
      - "4000:80"
    volumes:
      - "./video-streaming:/app:z"
      - "/tmp/video-streaming/python-cache:/root/.cache:z"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - HISTORY_HOST=history
      - HISTORY_PORT=80
      - FLASK_ENV=development
    restart: 'no'
    depends_on:
      - db

  video-storage:
    image: py-video-storage
    build:
      context: ./video-storage-azure
      dockerfile: Dockerfile
      target: dev
    container_name: py-video-storage
    ports:
      - "4001:80"
    volumes:
      - "./video-storage-azure:/app:z"
      - "/tmp/video-storage/python-cache:/root/.cache:z"
    environment:
      - PORT=80
      - FLASK_ENV=development
    restart: 'no'

  db:
    image: mongo:4.2
    container_name: py-db
    ports:
      - "4002:27017"
    restart: always

  history:
    image: py-history
    build:
      context: ./history
      dockerfile: Dockerfile
      target: dev
    container_name: py-history
    ports:
      - "4003:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - RABBIT=amqp://guest:guest@rabbit:5672
      - FLASK_ENV=development
    volumes:
      - "./history:/app:z"
      - "/tmp/history/python-cache:/root/.cache:z"
    restart: 'no'
    depends_on:
      - db

